# Generated by Django 4.0.2 on 2022-02-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('timetoread', models.CharField(max_length=255)),
                ('post', models.TextField(blank=True)),
                ('blog_image', models.ImageField(upload_to='Media/')),
            ],
        ),
    ]
