# Generated by Django 4.0.2 on 2022-02-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtbblog', '0002_alter_post_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
