# Generated by Django 4.0.2 on 2022-02-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtbblog', '0003_alter_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_image',
            new_name='image',
        ),
    ]
